FROM mongo

#COPY data/db data/db
#COPY nodejs-server/dump/ data/

#RUN mongoimport --host mongo:27017 --db api-data --collection users --type json --file="/data/api-data/users.json" --jsonArray
#RUN mongoimport --host mongo:27017 --db api-data --collection messages --type json --file="/data/api-data/messages.json" --jsonArray

#RUN  mongorestore --db api-data data/api-data
ENTRYPOINT mongod

#RUN mongorestore --host mongo --port 27017 /data/api-data

#RUN mongorestore

#CMD ["usr/bin/mongod"]
