version: "3"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8081:8081
    networks:
          - backend

  mongo:
    container_name: mongo
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - 27017
    volumes:
      - ./data:/data
    #command:
  #    - mongoimport --host mongo:27017 --db api-data --collection users --type json --file="/data/users.json" --jsonArray
  #    - mongoimport --host mongo:27017 --db api-data --collection messages --type json --file="/data/messages.json" --jsonArray
    #command:
    #  - mongorestore --host mongo --db api-datas
    #   - mongo

    networks:
          - backend


networks:
    backend: {}
